### ISSUE TITLE
add autoloading

### ISSUE THREAD

**Issue by wasthishelpful** [wasthishelpful/my-simple-mvc#4]
autoloading should be included following [PSR-4](https://www.php-fig.org/psr/psr-4/). Inspiration can be found in the [example files](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md).

`src` should be used a s a base directory to load classes.

**Comment by einnar82** [comment]
I will do this part.

**Comment by kimyvgy** [comment]
#11
